CREATE TABLE radio6.Genre (nomGenre VARCHAR(255) NOT NULL, PRIMARY KEY (nomGenre))
CREATE TABLE radio6.Pays (nomPays VARCHAR(255) NOT NULL, PRIMARY KEY (nomPays))
CREATE TABLE radio6.Chanteur (nomChanteur VARCHAR(255) NOT NULL, PRIMARY KEY (nomChanteur))
CREATE TABLE radio6.Symbole (nomSymbole VARCHAR(255) NOT NULL, PRIMARY KEY (nomSymbole))
CREATE TABLE radio6.Theme (nomTheme VARCHAR(255) NOT NULL, PRIMARY KEY (nomTheme))
CREATE TABLE radio6.Chanson (numChanson INTEGER NOT NULL, cheminFichier VARCHAR(255), classification INTEGER, nomChanson VARCHAR(255), nomFichier VARCHAR(255), periode INTEGER, nomChanteur VARCHAR(255), nomGenre VARCHAR(255), nomPays VARCHAR(255), nomSymbole VARCHAR(255), nomTheme VARCHAR(255), PRIMARY KEY (numChanson))
CREATE TABLE radio6.Utilisateur (login VARCHAR(255) NOT NULL, pass VARCHAR(255), PRIMARY KEY (login))
ALTER TABLE radio6.Chanson ADD CONSTRAINT FK_Chanson_nomGenre FOREIGN KEY (nomGenre) REFERENCES radio6.Genre (nomGenre)
ALTER TABLE radio6.Chanson ADD CONSTRAINT FK_Chanson_nomPays FOREIGN KEY (nomPays) REFERENCES radio6.Pays (nomPays)
ALTER TABLE radio6.Chanson ADD CONSTRAINT FK_Chanson_nomTheme FOREIGN KEY (nomTheme) REFERENCES radio6.Theme (nomTheme)
ALTER TABLE radio6.Chanson ADD CONSTRAINT FK_Chanson_nomSymbole FOREIGN KEY (nomSymbole) REFERENCES radio6.Symbole (nomSymbole)
ALTER TABLE radio6.Chanson ADD CONSTRAINT FK_Chanson_nomChanteur FOREIGN KEY (nomChanteur) REFERENCES radio6.Chanteur (nomChanteur)
